
server:
    port: 8080

zuul: 
    routes:
        backend:
            path: /api/**
            url: http://localhost:9000
            sensitive-headers:
    host:
        connect-timeout-millis: 2000
        socket-timeout-millis: 10000

spring:
    application:
        name: gateway
    session:
        store-type: jdbc

